version: '3'
services:
  api:
    container_name: todo-app-api
    build: ./api
    ports:
      - 5000:5000
    networks:
      - todo-app
  client:
    container_name: todo-app-client
    build: ./client
    ports:
      - 80:80
    networks:
      - todo-app
networks:
  todo-app:
    driver: bridge
