name: Api

on:
  push:
    branches: [ master ]
    
jobs:
  api:
    runs-on: ubuntu-latest
    env:
        MONGO_URL: ${{secrets.MONGO_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
        working-directory: api
      - run: npm run test
        working-directory: api
            
