name: Test

on:
  push:
    branches: [ master ]
    
jobs:
  client:
    runs-on: ubuntu-latest
    env: 
        VUE_APP_API_URL: ${{secrets.VUE_APP_API_URL}}
        REPO: self
        BRANCH: master
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: s0/git-publish-subdir-action@develop
        with:
          node-version: 14
      - run: npm i
        working-directory: client
      - run: npm run test:unit
        working-directory: client
      - run: npm run build
        working-directory: client
        
  api:
    runs-on: ubuntu-latest
    env:
        MONGO_URL: ${{secrets.MONGO_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
        working-directory: api
      - run: npm run test
        working-directory: api
            
